services:
    db:
      container_name: psql
      image: postgres:16.2
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      ports:
        - 5430:5432
      volumes:
        - ./script-database.sql:/docker-entrypoint-initdb.d/script-database.sql
        - vlpsqldb:/var/lib/postgresql/data

    redisparkbr:
      container_name: redisparkbr
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
#      volumes:
#        - redisparkbr:/root/redis
#        - redisparkbr:/usr/local/etc/redis/redis.conf


volumes:
  vlpsqldb:
#  redisparkbr:
